-- 보호소에서 중성화한 동물, 4가지 종류를 알아오는게 어려웠음...
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.ANIMAL_TYPE, ANIMAL_INS.NAME FROM ANIMAL_INS
INNER JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.SEX_UPON_INTAKE in ('Intact Male', 'Intact Female')
AND ANIMAL_OUTS.SEX_UPON_OUTCOME in ('Spayed Female', 'Neutered Male')

-- 있었는데요 없었습니다
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
ORDER BY ANIMAL_INS.DATETIME

-- NULL 처리하기
SELECT
ANIMAL_INS.ANIMAL_TYPE,
CASE WHEN ANIMAL_INS.NAME IS NULL THEN 'No name' ELSE ANIMAL_INS.NAME END,
ANIMAL_INS.SEX_UPON_INTAKE
FROM ANIMAL_INS
