
-- 1
SELECT   DATE_FORMAT(DATETIME,  '%H') AS HOUR
       , COUNT(ANIMAL_ID)  AS "COUNT"
FROM ANIMAL_OUTS
WHERE 1=1
AND DATE_FORMAT(DATETIME, '%H-%i') >= '09-00'
AND DATE_FORMAT(DATETIME, '%H-%i') <= '19-59'
GROUP BY DATE_FORMAT(DATETIME,  '%H')
ORDER BY DATE_FORMAT(DATETIME,  '%H') ASC
;

-- 2
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM CTE
    WHERE HOUR < 23
)

SELECT   C.HOUR
       , COUNT(ANIMAL_ID)  AS "COUNT"
FROM CTE C
LEFT JOIN ANIMAL_OUTS AO
ON C.HOUR = DATE_FORMAT(AO.DATETIME,  '%H') 
GROUP BY C.HOUR

-- 3 
SELECT AO.ANIMAL_ID, AO.NAME 
FROM ANIMAL_OUTS AO
WHERE NOT EXISTS ( SELECT * 
                  FROM ANIMAL_INS AI
                  WHERE AO.ANIMAL_ID = AI.ANIMAL_ID
                 )
                  
