SELECT
    i.ANIMAL_ID AS ANIMAL_ID,
    i.NAME AS NAME
FROM
    ANIMAL_INS i
INNER JOIN
    ANIMAL_OUTS o
    ON i.ANIMAL_ID = o.ANIMAL_ID
    AND i.DATETIME > o.DATETIME
ORDER BY
    i.DATETIME ASC;