-- 1
SELECT hour(DATETIME), count(*) FROM ANIMAL_OUTS
WHERE hour(DATETIME) >= 9 and hour(DATETIME) <= 19
GROUP BY hour(DATETIME)
ORDER BY hour(DATETIME)

-- 2
SELECT hour.hour, count(ANIMAL_OUTS.ANIMAL_ID) FROM (
SELECT 0 as hour UNION ALL
SELECT 1 UNION ALL
SELECT 2 UNION ALL
SELECT 3 UNION ALL
SELECT 4 UNION ALL
SELECT 5 UNION ALL
SELECT 6 UNION ALL
SELECT 7 UNION ALL
SELECT 8 UNION ALL
SELECT 9 UNION ALL
SELECT 10 UNION ALL
SELECT 11 UNION ALL
SELECT 12 UNION ALL
SELECT 13 UNION ALL
SELECT 14 UNION ALL
SELECT 15 UNION ALL
SELECT 16 UNION ALL
SELECT 17 UNION ALL
SELECT 18 UNION ALL
SELECT 19 UNION ALL
SELECT 20 UNION ALL
SELECT 21 UNION ALL
SELECT 22 UNION ALL
SELECT 23
) hour LEFT JOIN ANIMAL_OUTS on hour(ANIMAL_OUTS.DATETIME) = hour.hour
GROUP BY hour.hour
ORDER BY hour.hour

-- 3
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL
