SELECT
    ain.NAME AS NAME,
    ain.DATETIME AS DATETIME
FROM
    ANIMAL_INS ain
LEFT JOIN
    ANIMAL_OUTS aout
    ON ain.ANIMAL_ID = aout.ANIMAL_ID
WHERE
    aout.DATETIME IS NULL
ORDER BY
    ain.DATETIME ASC
LIMIT 3;